[StylePrimary]
H=(20*#Scale#)
InlineSetting=Face | #MainFont#
InlineSetting2=Weight | 100
InlineSetting3=Size | (10*#Scale#)
InlineSetting4=Color | #LocalColor#,255
AntiAlias=1
StringAlign=LeftCenter

[StyleSecondary]
H=(20*#Scale#)
InlineSetting=Face | #MainFont#
InlineSetting2=Weight | 100
InlineSetting3=Size | (12*#Scale#)
InlineSetting4=Color | #LocalColor#,200
AntiAlias=1
StringAlign=RightCenter
NumOfDecimals=1
Padding=0,0,(2*#Scale#),0

[StyleValue]
StringAlign=LeftCenter
InlineSetting=Face | #MainFont#
InlineSetting2=Weight | 100
InlineSetting3=Size | (32*#Scale#)
InlineSetting4=Color | #LocalColor#,255
AntiAlias=1
InlineSetting5=Shadow | 1 | 1 | 1 | 0,0,0,100
